export const CALENDAR = {
  SELECT_DATE: 'CALENDAR_SELECT_DATE',
  CHANGE_MONTH: 'CALENDAR_CHANGE_MONTH',
}

export const EDITOR = {
  TOGGLE: 'EDITOR_TOGGLE',
  FIELDS: {
    PARTICIPANT: 'EDITOR_FIELDS_PARTICIPANT',
    DESCRIPTION: 'EDITOR_FIELDS_DESCRIPTION',
  },
  SAVE: 'EDITOR_SAVE',
  EDIT: 'EDITOR_EDIT',
  REMOVE: 'EDITOR_REMOVE',
}
